---
title: "Coding_Sample_2"
output:
  pdf_document: default
  html_document: default
  word_document: default
date: "2023-10-24"
---

```{r message = FALSE}
# load packages
library(dplyr)
library(tidyverse)
library(stargazer)
library(sandwich)
library(stringr)
```

```{r}
# load datafile
data1 <- read.csv("/Users/martrinmunoz/Desktop/EconPredoc/Writing Samples/Cocaine Project/col_coc.csv")
# Let's summarize the data to see things like min, max, mean, median etc.
summary(data1)
```

```{r}
# let's rename some of the columns
data1 <-data1 %>%  
  rename(
    coca_prod =coca.production..ha.,
    eradication = erradication..ha.,
    price = europe.cocaine.wholesale.prices..US..per.kg.inflation.adjusted.to.20xx.euros.and.purity.adjusted.,
    agriculture = agriculture.livestock.price.index..2004.2006...
  )
# The year variables have an 'X' in front of them. Let's remove these.
for (i in 7:20){
  colnames(data1)[i] <- str_sub(colnames(data1)[i], 2, 5)
}
# identify columns that contain non-integer or non-numeric variables
data1 %>% 
  select_if(function(x) !is.numeric(x) & !is.integer(x)) %>% 
  colnames(.)
# let's print this column to see what is the problem 
head(data1[,"price"])
# The price variable has a '$' sign in front of each dollar amount that needs 
# to be removed. Let's remove it now
data1 <- data1 %>% 
  mutate(price =str_replace(price, "\\$", ""))
# Now we can convert price to a numeric variable
data1$price <- as.numeric(data1$price)
# Make sure this worked
class(data1$price)
```

```{r}
# Let's run a linear regression of coca production on all the variables except for
# price,agriculture, and year
model1 <- lm(coca_prod~.-price-agriculture-year, data = data1)
summary(model1)
# get model diagnostics
par(mfrow=c(2,2))
plot(model1, which=1:4)
# Notice that the standard errors are a bit heteroskedastic since we don't get a
# perfectly straight line in the bottom left graph
# Let's get heteroskedastic robust errors for our model
se1 <- vcovHC(model1, type = "HC1")
robust_se1 <- sqrt(diag(se1))
```

```{r results = 'asis'}
# Now let's report the linear regression in a nice table. We want this table to
# capitalize the first letter of the names of the independent variables.
# I will do this manually for the first few independent variables, but will
# use a specific function to capitalize the first letter of all entity fixed 
# effects in one go. I will first collect the entity fixed effects into a vector
# then I will apply the str_to_title function to capitalize the first letter of
# each element of the vector.
departments <- colnames(data1[,21:ncol(data1)])
departments <- str_to_title(departments)
# Now let's report the linear regression in a table. Note that the first three 
# independent variables are manually renamed, the time fixed effects are renamed
# using the rep function, and the entity fixed effects are renamed using the
# character vector created in the previous code chunk. Also notice that the 
# intercept is moved to the top of the table using the intercept.bottom argument.
stargazer(model1, type = 'latex', title = "OLS Regression: The effects of aerial 
          spraying on coca production", header=FALSE, se = list(NULL, robust_se1), 
          digits = 2, covariate.labels= c("Intercept", "Eradication", "Unemployment",
          rep(2003:2016), departments),
          intercept.bottom = FALSE, single.row = TRUE,
          dep.var.labels   = "Coca Production")
```

