---
title: "Anti-Coca Project Coding Sample"
output:
  pdf_document: default
  html_document: default
date: "2023-10-24"
---

```{r message = FALSE}
# load packages
library(dplyr)
library(tidyverse)
library(stargazer)
library(sandwich)
library(stringr)
```

```{r}
# load datafile
data1 <- read.csv("/Users/martrinmunoz/Desktop/EconPredoc/Writing Samples/Cocaine Project/col_coc.csv")
# summarize the data
summary(data1)
```

```{r}
# let's rename some of the columns
data1 <-data1 %>%  
  rename(
    coca_prod =coca.production..ha.,
    eradication = erradication..ha.,
    price = europe.cocaine.wholesale.prices..US..per.kg.inflation.adjusted.to.20xx.euros.and.purity.adjusted.,
    agriculture = agriculture.livestock.price.index..2004.2006...
  )
# The year variables have an 'X' in front of them. Let's remove these.
for (i in 7:20){
  colnames(data1)[i] <- str_sub(colnames(data1)[i], 2, 5)
}
# identify columns that contain non-integer or non-numeric variables
data1 %>% 
  select_if(function(x) !is.numeric(x) & !is.integer(x)) %>% 
  colnames(.)
# let's print these two columns to see what is the problem 
head(data1[,"eradication"])
head(data1[,"price"])
# The price variable has a '$' sign in front of each dollar amount that needs 
# to be removed. Let's remove it now
data1 <- data1 %>% 
  mutate(price =str_replace(price, "\\$", ""))
# Now we can convert price and eradication to numeric variables
data1$price <- as.numeric(data1$price)
data1$eradication <- as.numeric(data1$eradication)
# Make sure this worked
is.character(data1)
```

```{r}
# Let's run a linear regression of coca production on all the variables except for
# price,agriculture, and year
model1 <- lm(coca_prod~.-price-agriculture-year, data = data1)
summary(model1)
# get model diagnostics
par(mfrow=c(2,2))
plot(model1, which=1:4)
# Notice that the standard errors are a bit heteroskedastic since we don't get a
# perfectly straight line in the bottom left graph
# Let's get heteroskedastic robust errors for our model
se1 <- vcovHC(model1, type = "HC1")
robust_se1 <- sqrt(diag(se1))
```

```{r results = 'hide'}
# Now let's report the linear regression in a nice table. Note that this is
# generated as a separate .html file.
stargazer(model1, type = 'html', se = list(NULL, robust_se1), digits = 2, 
          title = 'OLS Regression', intercept.bottom = FALSE, single.row = TRUE,
          dep.var.labels   = "Cocaine Production", out = "output.html")
```

